// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.707
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Navigation() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<section class=\"w-full px-8 text-gray-700 bg-white\"><div class=\"container flex flex-col flex-wrap items-center justify-between py-5 mx-auto md:flex-row max-w-7xl\"><div class=\"relative flex flex-col md:flex-row\"><a href=\"#_\" class=\"flex items-center mb-5 font-medium text-gray-900 lg:w-auto lg:items-center lg:justify-center md:mb-0\"><span class=\"mx-auto text-xl font-black leading-none text-gray-900 select-none\">Goemon<span class=\"text-indigo-600\" data-primary=\"indigo-600\">.</span></span></a><nav class=\"flex flex-wrap items-center mb-5 text-base md:mb-0 md:pl-8 md:ml-8 md:border-l md:border-gray-200\"><a href=\"/\" class=\"mr-5 font-medium leading-6 text-gray-600 hover:text-gray-900\">Home</a> <a href=\"/features\" class=\"mr-5 font-medium leading-6 text-gray-600 hover:text-gray-900\">Features</a> <a href=\"/pricing\" class=\"mr-5 font-medium leading-6 text-gray-600 hover:text-gray-900\">Pricing</a> <a href=\"/blog\" class=\"mr-5 font-medium leading-6 text-gray-600 hover:text-gray-900\">Blog</a></nav></div><div class=\"inline-flex items-center ml-5 space-x-6 lg:justify-end\"><a href=\"#\" class=\"text-base font-medium leading-6 text-gray-600 whitespace-no-wrap transition duration-150 ease-in-out hover:text-gray-900\">Sign in</a> <a href=\"#\" class=\"inline-flex items-center justify-center px-4 py-2 text-base font-medium leading-6 text-white whitespace-no-wrap bg-indigo-600 border border-transparent rounded-md shadow-sm hover:bg-indigo-500 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-600\" data-rounded=\"rounded-md\" data-primary=\"indigo-600\">Sign up</a></div></div></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
